spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:changelog_init.xml
    enabled: true
    drop-first: true